package com.example.tgserver

import android.content.Context
import android.os.Build
import kotlinx.coroutines.flow.MutableStateFlow
import org.drinkless.td.libcore.telegram.Client
import org.drinkless.td.libcore.telegram.TdApi
import java.io.File

sealed class AuthState {
    object Idle : AuthState()
        object WaitPhone : AuthState()
            object WaitCode : AuthState()
                object WaitPassword : AuthState()
                    object Ready : AuthState()
                        data class Error(val message: String) : AuthState()
                        }

                        object TelegramClient {

                            val authState = MutableStateFlow<AuthState>(AuthState.Idle)

                                private var client: Client? = null
                                    
                                        // File listeners management (required by ChunkBridge.kt)
                                            private val fileListeners = mutableMapOf<Int, MutableList<(TdApi.File) -> Unit>>()
                                                private val listenersLock = Any()

                                                    // Exposed for TelegramFileResolver and ChunkBridge
                                                        fun rawClient(): Client? = client

                                                            fun addFileListener(fileId: Int, listener: (TdApi.File) -> Unit) {
                                                                    synchronized(listenersLock) {
                                                                                fileListeners.getOrPut(fileId) { mutableListOf() }.add(listener)
                                                                                        }
                                                                                            }

                                                                                                fun removeFileListener(fileId: Int, listener: (TdApi.File) -> Unit) {
                                                                                                        synchronized(listenersLock) {
                                                                                                                    fileListeners[fileId]?.remove(listener)
                                                                                                                                if (fileListeners[fileId]?.isEmpty() == true) {
                                                                                                                                                fileListeners.remove(fileId)
                                                                                                                                                            }
                                                                                                                                                                    }
                                                                                                                                                                        }

                                                                                                                                                                            fun init(context: Context, apiId: Int, apiHash: String) {
                                                                                                                                                                                    if (client != null) return

                                                                                                                                                                                            val dbDir = File(context.filesDir, "tdlib").absolutePath

                                                                                                                                                                                                    // Correct package: org.drinkless.td.libcore.telegram.Client
                                                                                                                                                                                                            client = Client.create({ update -> handleUpdate(update) }, null, null)

                                                                                                                                                                                                                    val parameters = TdApi.TdlibParameters().apply {
                                                                                                                                                                                                                                databaseDirectory = dbDir
                                                                                                                                                                                                                                            useFileDatabase = true
                                                                                                                                                                                                                                                        useChatInfoDatabase = true
                                                                                                                                                                                                                                                                    useMessageDatabase = true
                                                                                                                                                                                                                                                                                useSecretChats = false
                                                                                                                                                                                                                                                                                            this.apiId = apiId
                                                                                                                                                                                                                                                                                                        this.apiHash = apiHash
                                                                                                                                                                                                                                                                                                                    systemLanguageCode = "en"
                                                                                                                                                                                                                                                                                                                                deviceModel = "Android"
                                                                                                                                                                                                                                                                                                                                            systemVersion = Build.VERSION.RELEASE ?: "Unknown"
                                                                                                                                                                                                                                                                                                                                                        applicationVersion = "0.1"
                                                                                                                                                                                                                                                                                                                                                                    enableStorageOptimizer = true
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                    client?.send(TdApi.SetTdlibParameters(parameters)) { response ->
                                                                                                                                                                                                                                                                                                                                                                                                if (response is TdApi.Error) {
                                                                                                                                                                                                                                                                                                                                                                                                                authState.value = AuthState.Error("TDLib Init Error: ${response.message} (Code: ${response.code})")
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            fun submitPhone(phone: String) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    client?.send(TdApi.SetAuthenticationPhoneNumber(phone, null)) { response ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (response is TdApi.Error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                authState.value = AuthState.Error("Phone Error: ${response.message} (Code: ${response.code})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fun submitCode(code: String) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    client?.send(TdApi.CheckAuthenticationCode(code)) { response ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (response is TdApi.Error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                authState.value = AuthState.Error("Code Error: ${response.message} (Code: ${response.code})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fun submitPassword(password: String) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    client?.send(TdApi.CheckAuthenticationPassword(password)) { response ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (response is TdApi.Error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                authState.value = AuthState.Error("Password Error: ${response.message} (Code: ${response.code})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private fun handleUpdate(update: TdApi.Object) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    when (update) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                is TdApi.UpdateAuthorizationState -> handleAuthState(update.authorizationState)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            is TdApi.UpdateFile -> dispatchFileUpdate(update.file)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        is TdApi.Error -> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // CATCH-ALL: This catches silent TDLib crashes/errors so the UI doesn't freeze
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        authState.value = AuthState.Error("TDLib Error: ${update.message} (Code: ${update.code})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else -> { /* ignore other routine updates */ }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private fun handleAuthState(state: TdApi.AuthorizationState) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        when (state) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    is TdApi.AuthorizationStateWaitPhoneNumber -> authState.value = AuthState.WaitPhone
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                is TdApi.AuthorizationStateWaitCode -> authState.value = AuthState.WaitCode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            is TdApi.AuthorizationStateWaitPassword -> authState.value = AuthState.WaitPassword
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        is TdApi.AuthorizationStateReady -> authState.value = AuthState.Ready
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    is TdApi.AuthorizationStateClosed -> authState.value = AuthState.Error("Session closed unexpectedly")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                is TdApi.AuthorizationStateLoggingOut -> authState.value = AuthState.Error("Logging out...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else -> { /* WaitTdlibParameters and others are handled internally by TDLib */ }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private fun dispatchFileUpdate(file: TdApi.File) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    synchronized(listenersLock) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val listeners = fileListeners[file.id]?.toList() ?: emptyList()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (listener in listeners) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            listener(file)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }